/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = number;
export type Key = string;
export type Year = number;
export type Semester = 1 | 2 | 3;
export type Label = string;
export type GeneratedAt = string | null;
export type System = string;
export type BaseUrl = string;
export type CrawlerName = string;
export type CrawlerVersion = string;
export type GitSha = string | null;
export type CatalogCrawledAt = string | null;
export type EnrollmentObservedAt = string | null;
/**
 * 學期鍵，如 "115-1"
 */
export type TermKey = string;
/**
 * 課號（per-term 選課代碼，跳動）；= cwish subj
 */
export type OfferingId = string;
/**
 * 課程編碼（跨學期固定；同編碼可多課號=多班）
 */
export type CourseCode = string | null;
export type Zh = string;
export type En = string | null;
/**
 * 學分（含 0.5/0.0 佔位；加總時排除佔位課）
 */
export type Credits = number | null;
export type Hours = number | null;
export type Stage = number | null;
export type StageRaw = string | null;
export type Symbol = string | null;
/**
 * 修別語意（原始符號另存於 Requirement.symbol，category 須由課程標準對映、未知先 unknown）。
 */
export type RequirementCategory = "required" | "elective" | "general" | "program" | "unknown";
export type LabelZh = string | null;
/**
 * 學制大類（取代學長按中文檔名切分）。
 */
export type DivisionGroup = "day" | "extension" | "graduate" | "program" | "other";
export type UnitCode = string | null;
export type UnitName = string | null;
export type Code = string;
export type Name = string;
/**
 * 班級種類——分類地雷：pool/virtual 班學生班級碼永不在其中（博雅/體育/英文 ~12%）。
 */
export type ClassKind = "regular" | "pool" | "virtual";
export type UnitCode1 = string | null;
export type Grade = number | null;
/**
 * 開課班級（本班/外班分類用，含 kind）
 */
export type Classes = ClassRef[];
export type Code1 = string;
export type Name1 = string;
export type Teachers = EntityRef[];
export type Classrooms = EntityRef[];
export type Day = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type Periods = ("1" | "2" | "3" | "4" | "N" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D")[];
export type ClassroomCodes = string[];
export type WeekPattern = "weekly" | "odd" | "even" | "unknown";
export type DateRange = string | null;
export type Group = string | null;
export type RawText = string | null;
export type Meetings = Meeting[];
/**
 * 授課語言/EMI（來源第18欄，gnehs 漏抓）
 */
export type Language = string | null;
export type Tags = string[];
export type NotesRaw = string;
export type IsPlaceholder = boolean;
export type Interdisciplinary = string | null;
export type EnrolledCount = number | null;
export type Capacity = number | null;
export type WithdrawnCount = number | null;
export type ObservedAt = string | null;
export type CwishSubj = string;
export type CandidateCunums = string[];
export type CurrCode = string | null;
export type Syllabus = {
  [k: string]: string;
}[];
export type Courses = CourseOffering[];
export type SchemaVersion1 = number;
export type Timezone = string;
export type Token = "1" | "2" | "3" | "4" | "N" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D";
export type Order = number;
export type StartHm = string;
export type EndHm = string;
export type Label1 = string;
export type Periods1 = PeriodRef[];
export type SchemaVersion2 = number;
export type TermKey1 = string;
export type Classes1 = ClassRef[];
export type SchemaVersion3 = number;
export type TermKey2 = string;
export type ObservedAt1 = string | null;
export type SchemaVersion4 = number;
export type GeneratedAt1 = string | null;
export type MinAppVersion = string | null;
export type Url = string;
export type Sha256 = string;
export type Size = number;
export type ContentEncoding = string | null;
export type SchemaVersion5 = number;
export type DatasetVersion = string | null;
export type TermKey3 = string;
export type OfferingId1 = string;
export type CourseCode1 = string | null;
export type TeacherCode = string | null;
export type TeacherName = string;
export type Email = string | null;
export type OfficeHoursUrl = string | null;
export type UpdatedAt = string | null;
export type Outline = string | null;
export type Schedule = string | null;
export type Assessment = string | null;
export type Materials = string | null;
export type Consultation = string | null;
export type ExtendedResources = string | null;
export type Sdgs = string | null;
export type AiUsage = string | null;
export type Notes = string | null;
export type Syllabi = Syllabus1[];
export type GeneratedAt2 = string | null;
export type SchemaVersion6 = number;
export type TermKey4 = string;
export type Code2 = string;
export type Name2 = string;
export type OfferingIds = string[];
export type Programs = MicroProgram[];
export type SchemaVersion7 = number;
export type EntryYear = number;
export type EntryYear1 = number;
export type Matric = string;
export type Division = string;
export type Title = string;
export type StudyYear = number | null;
export type StudySem = number | null;
export type CourseCode2 = string | null;
export type NameZh = string;
export type Credits1 = number | null;
export type Hours1 = number | null;
export type Stage1 = string | null;
export type GroupId = string | null;
export type Notes1 = string;
export type Courses1 = StandardCourse[];
export type Programs1 = ProgramStandard[];

export interface NtutboxCourseV1 {
  TermCatalog?: TermCatalog;
  PeriodTable?: PeriodTable;
  ClassDirectory?: ClassDirectory;
  EnrollmentLatest?: EnrollmentLatest;
  Manifest?: Manifest;
  CourseDetail?: CourseDetail;
  MicroProgramDirectory?: MicroProgramDirectory;
  StandardDirectory?: StandardDirectory;
  [k: string]: unknown;
}
/**
 * catalog.json：Web v1 主檔（前端建索引）。重文字(描述/課綱)拆 course/{id}.json 隨點隨取。
 */
export interface TermCatalog {
  schema_version?: SchemaVersion;
  term: TermInfo;
  generated_at?: GeneratedAt;
  source?: SourceInfo;
  freshness?: Freshness;
  courses?: Courses;
  [k: string]: unknown;
}
export interface TermInfo {
  key: Key;
  year: Year;
  semester: Semester;
  label?: Label;
  [k: string]: unknown;
}
export interface SourceInfo {
  system?: System;
  base_url?: BaseUrl;
  crawler_name?: CrawlerName;
  crawler_version?: CrawlerVersion;
  git_sha?: GitSha;
  [k: string]: unknown;
}
export interface Freshness {
  catalog_crawled_at?: CatalogCrawledAt;
  enrollment_observed_at?: EnrollmentObservedAt;
  [k: string]: unknown;
}
/**
 * 一學期一門課一班的開課實例。主鍵＝(term_key, offering_id)。
 */
export interface CourseOffering {
  term_key: TermKey;
  offering_id: OfferingId;
  course_code?: CourseCode;
  name: LocalizedText;
  credits?: Credits;
  hours?: Hours;
  stage?: Stage;
  stage_raw?: StageRaw;
  requirement?: Requirement;
  division_group?: DivisionGroup | null;
  unit_code?: UnitCode;
  unit_name?: UnitName;
  classes?: Classes;
  teachers?: Teachers;
  classrooms?: Classrooms;
  meetings?: Meetings;
  language?: Language;
  tags?: Tags;
  notes_raw?: NotesRaw;
  is_placeholder?: IsPlaceholder;
  interdisciplinary?: Interdisciplinary;
  enrollment?: Enrollment;
  selection: Selection;
  source_refs?: SourceRefs | null;
  raw_fields?: RawFields;
}
export interface LocalizedText {
  zh?: Zh;
  en?: En;
  [k: string]: unknown;
}
export interface Requirement {
  symbol?: Symbol;
  category?: RequirementCategory;
  label_zh?: LabelZh;
  [k: string]: unknown;
}
/**
 * 開課班級 / classes.json 條目。班級碼 == cwish cunum（同命名空間、逐年重編）。
 */
export interface ClassRef {
  code: Code;
  name?: Name;
  kind?: ClassKind;
  unit_code?: UnitCode1;
  grade?: Grade;
  [k: string]: unknown;
}
/**
 * 教師/教室等實體：只留 code（丟棄學長的 JSP link，避免綁死校方路徑）。
 */
export interface EntityRef {
  code: Code1;
  name?: Name1;
  [k: string]: unknown;
}
/**
 * 單一上課時段。weekPattern/dateRange/教室對應＝來源未提供（§4.7）→ optional。
 */
export interface Meeting {
  day: Day;
  periods: Periods;
  classroom_codes?: ClassroomCodes;
  week_pattern?: WeekPattern;
  date_range?: DateRange;
  group?: Group;
  raw_text?: RawText;
  [k: string]: unknown;
}
/**
 * 人數（爬取當下快照）。⚠️ 容量上限來源不提供→capacity 多為 None，僅 cwish live 可補。
 */
export interface Enrollment {
  enrolled_count?: EnrolledCount;
  capacity?: Capacity;
  withdrawn_count?: WithdrawnCount;
  observed_at?: ObservedAt;
  [k: string]: unknown;
}
/**
 * 送件鍵。cunum 不放定值——實際 cunum 由 cwish live 本班/外班清單裁定（§4.6 實證）。
 */
export interface Selection {
  cwish_subj: CwishSubj;
  candidate_cunums?: CandidateCunums;
  [k: string]: unknown;
}
export interface SourceRefs {
  curr_code?: CurrCode;
  syllabus?: Syllabus;
  [k: string]: unknown;
}
export interface RawFields {
  [k: string]: string;
}
export interface PeriodTable {
  schema_version?: SchemaVersion1;
  timezone?: Timezone;
  periods?: Periods1;
  [k: string]: unknown;
}
/**
 * periods.json 條目：節次 token ↔ 牆鐘時間（Asia/Taipei），grid/ICS 用。
 */
export interface PeriodRef {
  token: Token;
  order: Order;
  start_hm: StartHm;
  end_hm: EndHm;
  label: Label1;
  [k: string]: unknown;
}
/**
 * classes.json：逐學期；Web 身分選擇器（系所/年級/班）+ 本班判斷；班級碼可預填 cwish cunum。
 */
export interface ClassDirectory {
  schema_version?: SchemaVersion2;
  term_key: TermKey1;
  classes?: Classes1;
  [k: string]: unknown;
}
/**
 * enrollment.json：volatile overlay；選課季可高頻更新，疊在已快取 catalog 上。
 */
export interface EnrollmentLatest {
  schema_version?: SchemaVersion3;
  term_key: TermKey2;
  observed_at?: ObservedAt1;
  counts?: Counts;
  [k: string]: unknown;
}
export interface Counts {
  [k: string]: Enrollment;
}
/**
 * manifest.json：client 先抓（極小），比對 sha256 決定要不要重抓。
 */
export interface Manifest {
  schema_version?: SchemaVersion4;
  generated_at?: GeneratedAt1;
  min_app_version?: MinAppVersion;
  terms?: Terms;
  [k: string]: unknown;
}
export interface Terms {
  [k: string]: ManifestTerm;
}
export interface ManifestTerm {
  catalog: ManifestEntry;
  enrollment?: ManifestEntry | null;
  classes?: ManifestEntry | null;
  periods?: ManifestEntry | null;
  mprograms?: ManifestEntry | null;
  dataset_version?: DatasetVersion;
  [k: string]: unknown;
}
export interface ManifestEntry {
  url: Url;
  sha256: Sha256;
  size: Size;
  content_encoding?: ContentEncoding;
  schema_version?: SchemaVersion5;
  [k: string]: unknown;
}
/**
 * 重文字詳情（描述 + 大綱），隨點隨取；與 catalog 分檔（catalog 保持輕、可搜尋）。
 */
export interface CourseDetail {
  term_key: TermKey3;
  offering_id: OfferingId1;
  course_code?: CourseCode1;
  name?: LocalizedText;
  description?: LocalizedText;
  syllabi?: Syllabi;
  generated_at?: GeneratedAt2;
}
/**
 * 單一教師的教學大綱（ShowSyllabus.jsp；label→textarea，用標籤文字定位）。
 */
export interface Syllabus1 {
  teacher_code?: TeacherCode;
  teacher_name?: TeacherName;
  email?: Email;
  office_hours_url?: OfficeHoursUrl;
  updated_at?: UpdatedAt;
  outline?: Outline;
  schedule?: Schedule;
  assessment?: Assessment;
  materials?: Materials;
  consultation?: Consultation;
  extended_resources?: ExtendedResources;
  sdgs?: Sdgs;
  ai_usage?: AiUsage;
  notes?: Notes;
  extra?: Extra;
  [k: string]: unknown;
}
export interface Extra {
  [k: string]: string;
}
/**
 * mprograms.json：逐學期微學程清單 + 各學程開課課號。
 */
export interface MicroProgramDirectory {
  schema_version?: SchemaVersion6;
  term_key: TermKey4;
  programs?: Programs;
  [k: string]: unknown;
}
/**
 * 微學程：SearchMProgram。offering_ids = 該學程該學期開課的課號。
 */
export interface MicroProgram {
  code: Code2;
  name: Name2;
  offering_ids?: OfferingIds;
  [k: string]: unknown;
}
/**
 * standards/{entry_year}.json：某入學年所有 program 的課程標準。
 */
export interface StandardDirectory {
  schema_version?: SchemaVersion7;
  entry_year: EntryYear;
  programs?: Programs1;
  [k: string]: unknown;
}
/**
 * 某入學年×學制×系所的課程標準/畢業標準（Cprog 葉節點）。
 */
export interface ProgramStandard {
  entry_year: EntryYear1;
  matric: Matric;
  division: Division;
  title?: Title;
  courses?: Courses1;
  [k: string]: unknown;
}
/**
 * 課程標準單列（Cprog format=-4）：某入學年/學制/系所的應修課程。
 */
export interface StandardCourse {
  study_year?: StudyYear;
  study_sem?: StudySem;
  requirement?: Requirement;
  course_code?: CourseCode2;
  name_zh?: NameZh;
  credits?: Credits1;
  hours?: Hours1;
  stage?: Stage1;
  group_id?: GroupId;
  notes?: Notes1;
  [k: string]: unknown;
}
