/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = number;
export type Key = string;
export type Year = number;
export type Semester = 1 | 2 | 3;
export type Label = string;
export type GeneratedAt = string | null;
export type System = string;
export type BaseUrl = string;
export type CrawlerName = string;
export type CrawlerVersion = string;
export type GitSha = string | null;
export type CatalogCrawledAt = string | null;
export type EnrollmentObservedAt = string | null;
/**
 * 學期鍵，如 "115-1"
 */
export type TermKey = string;
/**
 * 課號（per-term 選課代碼，跳動）；= cwish subj
 */
export type OfferingId = string;
/**
 * 課程編碼（跨學期固定；同編碼可多課號=多班）
 */
export type CourseCode = string | null;
export type Zh = string;
export type En = string | null;
/**
 * 學分（含 0.5/0.0 佔位；加總時排除佔位課）
 */
export type Credits = number | null;
export type Hours = number | null;
export type Stage = number | null;
export type StageRaw = string | null;
export type Symbol = string | null;
/**
 * 修別語意（原始符號另存於 Requirement.symbol，category 須由課程標準對映、未知先 unknown）。
 */
export type RequirementCategory = "required" | "elective" | "general" | "program" | "unknown";
export type LabelZh = string | null;
/**
 * 學制大類（取代學長按中文檔名切分）。
 *
 * ⚠️ 偏粗、會蓋掉「進修部」語意（如在職碩專班 matric=A 被歸 graduate）。
 * 顯示/學分規則請改用 CourseOffering.matric_division（matric 升級的第一級欄位）。
 * 暫留以免破壞既有消費者，日後 deprecate。
 */
export type DivisionGroup = "day" | "extension" | "graduate" | "program" | "other";
/**
 * 該課全部學制碼集合（跨多次查詢匯集）
 */
export type MatricCodes = string[];
export type Code = string;
export type Label1 = string;
/**
 * 體系（system）分類軸——與 DivisionGroup 正交，供學分規則用。
 *
 * 日間部={day}；進修部系統={extension, on_job}（含進修部碩士在職專班/週末碩/EMBA）。
 * 日間部學生的學分加總應排除非 day 體系的課（不同體系，與選課階段分類一致）。
 */
export type MatricSystem = "day" | "extension" | "on_job" | "other";
export type UnitCode = string | null;
export type UnitName = string | null;
export type Code1 = string;
export type Name = string;
/**
 * 班級種類——分類地雷：pool/virtual 班學生班級碼永不在其中（博雅/體育/英文 ~12%）。
 */
export type ClassKind = "regular" | "pool" | "virtual";
export type UnitCode1 = string | null;
export type Grade = number | null;
/**
 * 開課班級（本班/外班分類用，含 kind）
 */
export type Classes = ClassRef[];
export type Code2 = string;
export type Name1 = string;
export type Teachers = EntityRef[];
export type Classrooms = EntityRef[];
export type Day = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type Periods = ("1" | "2" | "3" | "4" | "N" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D")[];
export type ClassroomCodes = string[];
export type WeekPattern = "weekly" | "odd" | "even" | "unknown";
export type DateRange = string | null;
export type Group = string | null;
export type RawText = string | null;
export type Meetings = Meeting[];
/**
 * 授課語言/EMI（來源第18欄，gnehs 漏抓）
 */
export type Language = string | null;
export type Tags = string[];
export type NotesRaw = string;
export type IsPlaceholder = boolean;
export type Interdisciplinary = string | null;
export type EnrolledCount = number | null;
export type Capacity = number | null;
export type WithdrawnCount = number | null;
export type ObservedAt = string | null;
export type CwishSubj = string;
export type CandidateCunums = string[];
export type CurrCode = string | null;
export type Syllabus = {
  [k: string]: string;
}[];
export type Courses = CourseOffering[];
export type SchemaVersion1 = number;
export type Timezone = string;
export type Token = "1" | "2" | "3" | "4" | "N" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D";
export type Order = number;
export type StartHm = string;
export type EndHm = string;
export type Label2 = string;
export type Periods1 = PeriodRef[];
export type SchemaVersion2 = number;
export type TermKey1 = string;
export type Classes1 = ClassRef[];
export type SchemaVersion3 = number;
export type TermKey2 = string;
export type ObservedAt1 = string | null;
export type SchemaVersion4 = number;
export type GeneratedAt1 = string | null;
export type PublishedAt = string | null;
export type MinAppVersion = string | null;
export type Url = string;
export type Sha256 = string;
export type Size = number;
export type ContentEncoding = string | null;
export type SchemaVersion5 = number;
export type CheckedAt = string | null;
export type ChangedAt = string | null;
export type Count = number | null;
export type Url1 = string;
export type Sha2561 = string;
export type Size1 = number;
export type ContentEncoding1 = string | null;
export type SchemaVersion6 = number;
export type CheckedAt1 = string | null;
export type ChangedAt1 = string | null;
export type CheckedAt2 = string | null;
export type ChangedAt2 = string | null;
export type Count1 = number;
export type DatasetVersion = string | null;
export type Url2 = string;
export type Sha2562 = string;
export type Size2 = number;
export type ContentEncoding2 = string | null;
export type SchemaVersion7 = number;
export type CheckedAt3 = string | null;
export type ChangedAt3 = string | null;
export type FirstWeekStart = string;
export type LastWeekEnd = string;
export type Term = string;
export type From = string;
export type Current = TermScheduleEntry[];
export type Default = TermScheduleEntry[];
export type TermKey3 = string;
export type OfferingId1 = string;
export type CourseCode1 = string | null;
export type TeacherCode = string | null;
export type TeacherName = string;
export type Email = string | null;
export type OfficeHoursUrl = string | null;
export type UpdatedAt = string | null;
export type Outline = string | null;
export type Schedule = string | null;
export type Assessment = string | null;
export type Materials = string | null;
export type Consultation = string | null;
export type ExtendedResources = string | null;
export type Sdgs = string | null;
export type AiUsage = string | null;
export type Notes = string | null;
export type Label3 = string;
export type Value = string;
export type FlexLearning = LabeledValue[];
export type Extra = LabeledValue[];
export type Status = "resolved" | "partial" | "unparsed";
export type Week = number;
export type Topics = string[];
export type SourceLines = string[];
export type Weeks = WeeklyProgressWeek[];
export type Notes1 = string[];
export type ParserVersion = string;
export type SourceScheduleSha256 = string;
export type Syllabi = Syllabus1[];
export type SchemaVersion8 = number;
export type TermKey4 = string;
export type Code3 = string;
export type Name2 = string;
export type OfferingIds = string[];
export type CourseCode2 = string;
export type NameZh = string;
export type Credits1 = number | null;
export type Category = ("基礎" | "核心" | "總整" | "進階" | "應用") | null;
export type CategoryRaw = string | null;
export type Online = boolean;
export type Courses1 = MicroProgramCourse[];
export type RulesText = string | null;
export type Programs = MicroProgram[];
export type SchemaVersion9 = number;
export type EntryYear = number;
export type EntryYear1 = number;
export type Matric = string;
export type Division = string;
export type Title = string;
export type StudyYear = number | null;
export type StudySem = number | null;
export type CourseCode3 = string | null;
export type NameZh1 = string;
export type Credits2 = number | null;
export type Hours1 = number | null;
export type Stage1 = string | null;
export type GroupId = string | null;
export type Notes2 = string;
export type Courses2 = StandardCourse[];
export type Programs1 = ProgramStandard[];
export type SchemaVersion10 = number;
export type Timezone1 = string;
export type RangeEndSemantics = "inclusive";
export type GeneratedAt2 = string | null;
export type Type = string;
export type Url3 = string;
export type ContentSha256 = string;
export type FetchedAt = string;
export type ParserVersion1 = string;
export type MaxStart = string;
export type Ok = boolean;
export type CheckedAt4 = string;
export type Uid = string;
export type Summary = string;
export type AllDay = boolean;
export type StartDate = string | null;
export type EndDate = string | null;
export type StartAt = string | null;
export type EndAt = string | null;
export type Description = string | null;
export type Location = string | null;
export type Sequence = number | null;
export type LastModified = string | null;
export type Events = CalendarEvent[];
export type SchemaVersion11 = number;
export type Timezone2 = string;
export type WeekStartsOn = "sunday";
export type RangeEndSemantics1 = "inclusive";
export type GeneratedAt3 = string | null;
export type Type1 = string;
export type Url4 = string;
export type ContentSha2561 = string;
export type ParsedAt = string;
export type ParserVersion2 = string;
export type DerivedFields = string[];
export type AdministrativeStart = string | null;
export type Start = string;
export type End = string;
export type InstructionStart = string;
export type Number = number;
export type Start1 = string;
export type End1 = string;
export type Weeks1 = TermWeek[];
export type BreakStart = string;
export type Kind = "preselection" | "freshman_preselection" | "post_start_add_drop" | "midterm_withdrawal";
export type TargetTerm = string;
export type Division1 = "day" | "evening" | "all";
export type Start2 = string;
export type End2 = string;
export type SourceUids = string[];
export type EnrollmentWindows = EnrollmentWindow[];
export type SchemaVersion12 = number;
export type TermKey5 = string;
export type UpdateSequence = number | null;
export type CampusMapManifestSha256 = string | null;
export type CampusRevision = string | null;
export type CampusSha256 = string | null;
export type BuildingId = string;
export type Label4 = string;
export type Order1 = number | null;
export type Buildings = TermRoomBuilding[];
export type Code4 = string;
export type Raw = string;
export type FullName = string | null;
export type Capacity1 = number | null;
export type Day1 = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type Period = "1" | "2" | "3" | "4" | "N" | "5" | "6" | "7" | "8" | "9" | "A" | "B" | "C" | "D";
export type OfferingIds1 = string[];
export type Slots = RoomSlot[];
export type BuildingId1 = string;
export type FloorId = string | null;
export type ClassNumber = string | null;
export type Gis = RoomGisRef[];
export type GisMatch = "rule" | "override" | "building_only" | "floor_only" | "none";
export type Rooms = TermRoom[];

export interface NtutboxCourseV1 {
  TermCatalog?: TermCatalog;
  PeriodTable?: PeriodTable;
  ClassDirectory?: ClassDirectory;
  EnrollmentLatest?: EnrollmentLatest;
  Manifest?: Manifest;
  CourseDetail?: CourseDetail;
  MicroProgramDirectory?: MicroProgramDirectory;
  StandardDirectory?: StandardDirectory;
  CalendarEventsFeed?: CalendarEventsFeed;
  TermCalendarFile?: TermCalendarFile;
  TermRooms?: TermRooms;
  [k: string]: unknown;
}
/**
 * catalog.json：Web v1 主檔（前端建索引）。重文字(描述/課綱)拆 course/{id}.json 隨點隨取。
 */
export interface TermCatalog {
  schema_version?: SchemaVersion;
  term: TermInfo;
  generated_at?: GeneratedAt;
  source?: SourceInfo;
  freshness?: Freshness;
  courses?: Courses;
  [k: string]: unknown;
}
export interface TermInfo {
  key: Key;
  year: Year;
  semester: Semester;
  label?: Label;
  [k: string]: unknown;
}
export interface SourceInfo {
  system?: System;
  base_url?: BaseUrl;
  crawler_name?: CrawlerName;
  crawler_version?: CrawlerVersion;
  git_sha?: GitSha;
  [k: string]: unknown;
}
export interface Freshness {
  catalog_crawled_at?: CatalogCrawledAt;
  enrollment_observed_at?: EnrollmentObservedAt;
  [k: string]: unknown;
}
/**
 * 一學期一門課一班的開課實例。主鍵＝(term_key, offering_id)。
 */
export interface CourseOffering {
  term_key: TermKey;
  offering_id: OfferingId;
  course_code?: CourseCode;
  name: LocalizedText;
  credits?: Credits;
  hours?: Hours;
  stage?: Stage;
  stage_raw?: StageRaw;
  requirement?: Requirement;
  division_group?: DivisionGroup | null;
  matric_codes?: MatricCodes;
  /**
   * 升級後的可顯示學制：中文標籤 + 體系（多碼依優先序裁定，無碼為 None）
   */
  matric_division?: MatricDivision | null;
  unit_code?: UnitCode;
  unit_name?: UnitName;
  classes?: Classes;
  teachers?: Teachers;
  classrooms?: Classrooms;
  meetings?: Meetings;
  language?: Language;
  tags?: Tags;
  notes_raw?: NotesRaw;
  is_placeholder?: IsPlaceholder;
  interdisciplinary?: Interdisciplinary;
  enrollment?: Enrollment;
  selection: Selection;
  source_refs?: SourceRefs | null;
  raw_fields?: RawFields;
}
export interface LocalizedText {
  zh?: Zh;
  en?: En;
  [k: string]: unknown;
}
export interface Requirement {
  symbol?: Symbol;
  category?: RequirementCategory;
  label_zh?: LabelZh;
  [k: string]: unknown;
}
/**
 * 學制（matric）升為第一級的可顯示欄位：逐碼中文標籤 + 體系軸。
 *
 * code = 被選中的單一 matric 碼（多碼時依優先序裁定，見 MATRIC_LABELS 註解）；
 * label = 該碼中文學制（如「進修部碩士在職專班」）；system = 體系（學分規則用）。
 * 無 matric 碼 → CourseOffering.matric_division 為 None。
 */
export interface MatricDivision {
  code: Code;
  label: Label1;
  system: MatricSystem;
  [k: string]: unknown;
}
/**
 * 開課班級 / classes.json 條目。班級碼 == cwish cunum（同命名空間、逐年重編）。
 */
export interface ClassRef {
  code: Code1;
  name?: Name;
  kind?: ClassKind;
  unit_code?: UnitCode1;
  grade?: Grade;
  [k: string]: unknown;
}
/**
 * 教師/教室等實體：只留 code（丟棄學長的 JSP link，避免綁死校方路徑）。
 */
export interface EntityRef {
  code: Code2;
  name?: Name1;
  [k: string]: unknown;
}
/**
 * 單一上課時段。weekPattern/dateRange＝來源未提供（§4.7）→ optional；教室對應由 derive 反查（D24）。
 */
export interface Meeting {
  day: Day;
  periods: Periods;
  classroom_codes?: ClassroomCodes;
  week_pattern?: WeekPattern;
  date_range?: DateRange;
  group?: Group;
  raw_text?: RawText;
  [k: string]: unknown;
}
/**
 * 人數（爬取當下快照）。⚠️ 容量上限來源不提供→capacity 多為 None，僅 cwish live 可補。
 */
export interface Enrollment {
  enrolled_count?: EnrolledCount;
  capacity?: Capacity;
  withdrawn_count?: WithdrawnCount;
  observed_at?: ObservedAt;
  [k: string]: unknown;
}
/**
 * 送件鍵。cunum 不放定值——實際 cunum 由 cwish live 本班/外班清單裁定（§4.6 實證）。
 */
export interface Selection {
  cwish_subj: CwishSubj;
  candidate_cunums?: CandidateCunums;
  [k: string]: unknown;
}
export interface SourceRefs {
  curr_code?: CurrCode;
  syllabus?: Syllabus;
  [k: string]: unknown;
}
export interface RawFields {
  [k: string]: string;
}
export interface PeriodTable {
  schema_version?: SchemaVersion1;
  timezone?: Timezone;
  periods?: Periods1;
  [k: string]: unknown;
}
/**
 * periods.json 條目：節次 token ↔ 牆鐘時間（Asia/Taipei），grid/ICS 用。
 */
export interface PeriodRef {
  token: Token;
  order: Order;
  start_hm: StartHm;
  end_hm: EndHm;
  label: Label2;
  [k: string]: unknown;
}
/**
 * classes.json：逐學期；Web 身分選擇器（系所/年級/班）+ 本班判斷；班級碼可預填 cwish cunum。
 */
export interface ClassDirectory {
  schema_version?: SchemaVersion2;
  term_key: TermKey1;
  classes?: Classes1;
  [k: string]: unknown;
}
/**
 * enrollment.json：volatile overlay；選課季可高頻更新，疊在已快取 catalog 上。
 */
export interface EnrollmentLatest {
  schema_version?: SchemaVersion3;
  term_key: TermKey2;
  observed_at?: ObservedAt1;
  counts?: Counts;
  [k: string]: unknown;
}
export interface Counts {
  [k: string]: Enrollment;
}
/**
 * manifest.json：client 先抓（極小），比對 sha256 決定要不要重抓。
 */
export interface Manifest {
  schema_version?: SchemaVersion4;
  generated_at?: GeneratedAt1;
  published_at?: PublishedAt;
  min_app_version?: MinAppVersion;
  terms?: Terms;
  calendars?: Calendars;
  term_schedule?: TermSchedule | null;
  [k: string]: unknown;
}
export interface Terms {
  [k: string]: ManifestTerm;
}
export interface ManifestTerm {
  catalog: CatalogManifestEntry;
  enrollment?: ManifestEntry | null;
  classes?: ManifestEntry | null;
  periods?: ManifestEntry | null;
  mprograms?: ManifestEntry | null;
  calendar?: ManifestEntry | null;
  rooms?: ManifestEntry | null;
  details?: DetailsFreshness | null;
  dataset_version?: DatasetVersion;
  [k: string]: unknown;
}
/**
 * `terms.{t}.catalog`：ManifestEntry 加上課數。
 *
 * publish 的品質閘門以**線上** manifest 的 `count` 為基準（S3 GetObject 直讀 bucket），
 * 本次 derive 出來的課數跌破基準 × 0.95 就不發佈。純新增欄位，不升 schema_version。
 * 舊 manifest 沒有這個鍵 → Optional，閘門此時只檢查「不為 0」。
 */
export interface CatalogManifestEntry {
  url: Url;
  sha256: Sha256;
  size: Size;
  content_encoding?: ContentEncoding;
  schema_version?: SchemaVersion5;
  checked_at?: CheckedAt;
  changed_at?: ChangedAt;
  count?: Count;
  [k: string]: unknown;
}
export interface ManifestEntry {
  url: Url1;
  sha256: Sha2561;
  size: Size1;
  content_encoding?: ContentEncoding1;
  schema_version?: SchemaVersion6;
  checked_at?: CheckedAt1;
  changed_at?: ChangedAt1;
  [k: string]: unknown;
}
/**
 * `terms.{t}.details`：課程詳情（`course/{id}.json`）的新鮮度。
 *
 * 沒有 url——單課檔是逐課隨點隨取的，manifest 不逐一列出；這裡只讓 client 知道
 * 「這學期的詳情最後一次確認／變動是什麼時候、有幾門」。
 */
export interface DetailsFreshness {
  checked_at?: CheckedAt2;
  changed_at?: ChangedAt2;
  count: Count1;
  [k: string]: unknown;
}
export interface Calendars {
  [k: string]: CalendarManifestEntry;
}
/**
 * `manifest.calendars` 的條目：ManifestEntry 加上「這份週次表涵蓋哪段日期」。
 *
 * 帶範圍是為了讓 App **只讀 manifest 就能挑出該抓哪一份**，不必把「8/1 學年度界線」
 * 或學期編號慣例複製進 App——那一側要送審才能改（App 端 2026-09-19 指出）。
 * App 的規則因此只剩通用的日期比對：找範圍涵蓋今天的那一筆。
 *
 * 範圍是**授課週**（第 1 週起日 ~ 末週迄日），不含準備週與假期。所以學期之間
 * （例如 1/11~1/31）不會有任何一筆涵蓋今天——那是真實的空窗，不是資料缺漏。
 */
export interface CalendarManifestEntry {
  url: Url2;
  sha256: Sha2562;
  size: Size2;
  content_encoding?: ContentEncoding2;
  schema_version?: SchemaVersion7;
  checked_at?: CheckedAt3;
  changed_at?: ChangedAt3;
  first_week_start: FirstWeekStart;
  last_week_end: LastWeekEnd;
  [k: string]: unknown;
}
/**
 * `manifest.term_schedule`（D21）：client 取 `from ≤ now` 的最後一筆。
 *
 * - `current`：本學期（8/1～1/31 上學期、2/1～7/31 下學期）。
 * - `default`：網站預設顯示的學期——本學期的期中撤選截止（日／夜間部取晚者）起改為下學期；
 *   無撤選窗口時退用下學期預選開始 − 14 天。
 * 由 derive 從 calendar.json 確定性產生（不讀系統時間，`ntut_catalog/term_schedule.py`）。
 * 學期可能還沒有 catalog（不在 `terms`）——client 此時退回本學期、再退回 `terms` 最新者。
 */
export interface TermSchedule {
  current?: Current;
  default?: Default;
  [k: string]: unknown;
}
/**
 * 時間軸的一格：自 `from`（ISO 8601 +08:00）起生效的學期，直到下一格的 `from`。
 */
export interface TermScheduleEntry {
  term: Term;
  from: From;
  [k: string]: unknown;
}
/**
 * 重文字詳情（描述 + 大綱），隨點隨取；與 catalog 分檔（catalog 保持輕、可搜尋）。
 */
export interface CourseDetail {
  term_key: TermKey3;
  offering_id: OfferingId1;
  course_code?: CourseCode1;
  name?: LocalizedText;
  description?: LocalizedText;
  syllabi?: Syllabi;
}
/**
 * 單一教師的教學大綱（ShowSyllabus.jsp；label→textarea，用標籤文字定位）。
 */
export interface Syllabus1 {
  teacher_code?: TeacherCode;
  teacher_name?: TeacherName;
  email?: Email;
  office_hours_url?: OfficeHoursUrl;
  updated_at?: UpdatedAt;
  outline?: Outline;
  schedule?: Schedule;
  assessment?: Assessment;
  materials?: Materials;
  consultation?: Consultation;
  extended_resources?: ExtendedResources;
  sdgs?: Sdgs;
  ai_usage?: AiUsage;
  notes?: Notes;
  flex_learning?: FlexLearning;
  extra?: Extra;
  weekly_progress?: WeeklyProgress | null;
  [k: string]: unknown;
}
/**
 * 「上游決定欄位」的 pass-through 單元：原樣搬來源的標籤與值。
 *
 * 刻意是**有序陣列的元素**而不是 dict entry：
 *   - 順序即來源表格列序，是契約的一部分（消費端照序渲染，不必知道欄位名）。
 *     dict 給不了這個保證——Swift 的 Dictionary 本質無序，JSONDecoder 一解完
 *     來源順序就沒了。
 *   - 重複標籤兩列都留，不會後者覆蓋前者（來源表格改版時最常見的靜默掉資料）。
 * 標籤**不映射、不正規化**，改名或新增欄位時解析與 UI 都自動跟隨。
 */
export interface LabeledValue {
  label: Label3;
  value: Value;
}
/**
 * `schedule` 自由文字的結構化衍生欄位。**原文 `schedule` 一律保留、不覆寫。**
 *
 * 三態的意義（App 要能誠實顯示，不能把「教師沒寫」顯示成「載入中」）：
 *   resolved  1..week_count 每一週都恰好一筆結果（missing = 0、ambiguous = 0）
 *   partial   至少一週有結果，但存在 missing 或原本 ambiguous 的週次
 *   unparsed  沒有任何一週能 resolve，含 schedule 為空、TBA、以及明確拒絕的樣態
 *             —— 這一態**仍要寫出來**（帶 parser_version）
 *
 * 衍生資料的身分鍵是 (term_key, offering_id, teacher_code, source_schedule_sha256)；
 * source_schedule_sha256 或 parser_version 一變就必須重產。
 */
export interface WeeklyProgress {
  status: Status;
  weeks?: Weeks;
  notes?: Notes1;
  parser_version: ParserVersion;
  source_schedule_sha256: SourceScheduleSha256;
  [k: string]: unknown;
}
export interface WeeklyProgressWeek {
  week: Week;
  topics: Topics;
  source_lines: SourceLines;
  [k: string]: unknown;
}
/**
 * mprograms.json：逐學期微學程清單 + 各學程開課課號。
 */
export interface MicroProgramDirectory {
  schema_version?: SchemaVersion8;
  term_key: TermKey4;
  programs?: Programs;
  [k: string]: unknown;
}
/**
 * 微學程：SearchMProgram。offering_ids = 該學程該學期開課的課號。
 */
export interface MicroProgram {
  code: Code3;
  name: Name2;
  offering_ids?: OfferingIds;
  courses?: Courses1;
  rules_text?: RulesText;
  [k: string]: unknown;
}
/**
 * 微學程課程標準列（Cprog -4，matric=H）。
 */
export interface MicroProgramCourse {
  course_code: CourseCode2;
  name_zh?: NameZh;
  credits?: Credits1;
  category?: Category;
  category_raw?: CategoryRaw;
  online?: Online;
  [k: string]: unknown;
}
/**
 * standards/{entry_year}.json：某入學年所有 program 的課程標準。
 */
export interface StandardDirectory {
  schema_version?: SchemaVersion9;
  entry_year: EntryYear;
  programs?: Programs1;
  [k: string]: unknown;
}
/**
 * 某入學年×學制×系所的課程標準/畢業標準（Cprog 葉節點）。
 */
export interface ProgramStandard {
  entry_year: EntryYear1;
  matric: Matric;
  division: Division;
  title?: Title;
  courses?: Courses2;
  [k: string]: unknown;
}
/**
 * 課程標準單列（Cprog format=-4）：某入學年/學制/系所的應修課程。
 */
export interface StandardCourse {
  study_year?: StudyYear;
  study_sem?: StudySem;
  requirement?: Requirement;
  course_code?: CourseCode3;
  name_zh?: NameZh1;
  credits?: Credits2;
  hours?: Hours1;
  stage?: Stage1;
  group_id?: GroupId;
  notes?: Notes2;
  [k: string]: unknown;
}
/**
 * v1/calendar/events.json：全量單檔（gzip 後約 25-35 KB）。
 */
export interface CalendarEventsFeed {
  schema_version?: SchemaVersion10;
  timezone?: Timezone1;
  range_end_semantics?: RangeEndSemantics;
  generated_at?: GeneratedAt2;
  source: CalendarSource;
  horizon: CalendarHorizon;
  events?: Events;
  [k: string]: unknown;
}
export interface CalendarSource {
  type?: Type;
  url: Url3;
  content_sha256: ContentSha256;
  fetched_at: FetchedAt;
  parser_version: ParserVersion1;
  [k: string]: unknown;
}
/**
 * feed 涵蓋到多遠。判準是 max(DTSTART) >= 次年 6 月，不是「有沒有新學年的事件」——
 * 112 學年度的下學期拖到 2024-02 才進來，看到新學年不等於整學年到位。
 */
export interface CalendarHorizon {
  max_start: MaxStart;
  ok: Ok;
  checked_at: CheckedAt4;
  [k: string]: unknown;
}
/**
 * 一筆行事曆事件。日期語意固定 inclusive，全天與有時刻用不同欄位、不混用。
 *
 * 來源是校網公開的 Google Calendar ics。**summary 逐字保留、不做任何正規化**
 * （不 trim、不 pangu、不改標點）——App 端有三處靠中文關鍵字反推語意，
 * 發布端再加一層改寫會讓它們靜默失效。
 */
export interface CalendarEvent {
  uid: Uid;
  summary: Summary;
  all_day: AllDay;
  start_date?: StartDate;
  end_date?: EndDate;
  start_at?: StartAt;
  end_at?: EndAt;
  description?: Description;
  location?: Location;
  sequence?: Sequence;
  last_modified?: LastModified;
  [k: string]: unknown;
}
/**
 * terms/{term}/calendar.json：逐學期一檔。
 *
 * 檔案是逐學期的，裡面卻仍保留單鍵的 `terms` map——這是為了讓 App 現行 decoder
 * （NTUTBox/Services/TermCalendarProvider.swift:119-163）一行都不用改。
 * 代價是多一層巢狀，換到的是換來源時 App 端零改動。
 */
export interface TermCalendarFile {
  schema_version?: SchemaVersion11;
  timezone?: Timezone2;
  week_starts_on?: WeekStartsOn;
  range_end_semantics?: RangeEndSemantics1;
  generated_at?: GeneratedAt3;
  source: TermCalendarSource;
  terms?: Terms1;
  [k: string]: unknown;
}
export interface TermCalendarSource {
  type?: Type1;
  url: Url4;
  content_sha256: ContentSha2561;
  parsed_at: ParsedAt;
  parser_version: ParserVersion2;
  derived_fields?: DerivedFields;
  [k: string]: unknown;
}
export interface Terms1 {
  [k: string]: AcademicTerm;
}
/**
 * 單一學期的行事曆。
 *
 * 四個 required 欄位不是隨意訂的：App 現在有三處靠中文事件標題反推語意
 * （VacationQuietLogic、detectSemesterRange、TermCalendarCrossCheck），
 * 要它們改讀結構化欄位，發布端就必須保證這些欄位一定在（不變量⑨）。
 */
export interface AcademicTerm {
  administrative_start?: AdministrativeStart;
  preparation?: DateRange1 | null;
  instruction_start: InstructionStart;
  weeks?: Weeks1;
  midterm: DateRange1;
  final_exam: DateRange1;
  flexible_learning?: DateRange1 | null;
  break_start: BreakStart;
  enrollment_windows?: EnrollmentWindows;
  [k: string]: unknown;
}
/**
 * inclusive 區間。ics 的全天事件是 end-exclusive，轉進來時已減一天。
 */
export interface DateRange1 {
  start: Start;
  end: End;
  [k: string]: unknown;
}
/**
 * 週次表單列。App 用 `number`，**不要改叫 index**
 * （NTUTBox/Models/AcademicTermCalendar.swift:22-64）。
 */
export interface TermWeek {
  number: Number;
  start: Start1;
  end: End1;
  [k: string]: unknown;
}
/**
 * 選課相關窗口（issue #111）：由 ics 具名事件推導，season 排程（ops/season-schedule.json）的來源。
 *
 * - **歸屬＝發生的學期（host term）**：窗口開始日所在的學期（8～1 月＝上學期、2～7 月＝下學期），
 *   寫進該學期的 calendar.json。
 * - `target_term`：**被選課的學期**。`preselection`（預選，校方行事曆稱「網路選課」）在前一學期
 *   期末舉行、選的是下學期的課：「115學年度第2學期網路選課」12/07 → 放在 115-1 的檔、
 *   `target_term` 115-2。其餘（`freshman_preselection` 新生預選、`post_start_add_drop` 開學後加退選、
 *   `midterm_withdrawal` 期中撤選）`target_term` 就是所在學期。season 排程與 daily 的 `active`
 *   學期規則都看 `target_term`。
 * - kind 不用裸 `add_drop`：那是選課階段分類裡 oads 系統的名字（CLAUDE.md），兩者不同。
 * - `division`：日間部 `day`、進修部 `evening`、標題未分部別 `all`。
 * - `start`／`end`：ISO-8601 +08:00 的**時刻**（不是日期）。事件沒寫時刻時，截止日間部
 *   17:00、進修部 21:00（標題「(17:00 截止)」這類註記優先）。
 */
export interface EnrollmentWindow {
  kind: Kind;
  target_term: TargetTerm;
  division: Division1;
  start: Start2;
  end: End2;
  source_uids?: SourceUids;
  [k: string]: unknown;
}
/**
 * v1 `terms/{t}/rooms.json`（北科盒子 App 的空教室查找）。
 *
 * 語意：slot＝「有排課」，不是「被占用」；沒有 slot 的時段不保證空著。
 */
export interface TermRooms {
  schema_version?: SchemaVersion12;
  term_key: TermKey5;
  gis_snapshot?: GisSnapshotInfo;
  buildings?: Buildings;
  rooms?: Rooms;
  [k: string]: unknown;
}
/**
 * 對應所依據的 GIS 版本。
 *
 * 來源是 canonical `gis/gis-rooms.json`（`campus_gis` 資料集鏡像 ntutbox-campus 的 CDN，D28）；
 * canonical 沒有時退回套件內凍結的 `reference/gis-rooms.fallback.json`（D23 的舊快照）。
 */
export interface GisSnapshotInfo {
  update_sequence?: UpdateSequence;
  campus_map_manifest_sha256?: CampusMapManifestSha256;
  campus_revision?: CampusRevision;
  campus_sha256?: CampusSha256;
  [k: string]: unknown;
}
/**
 * v1 rooms.json 的大樓清單名稱與排序（取自 ntutbox-campus gis-rooms 的 `label`／`order`，D28）。
 *
 * 只列該學期教室 GIS 對應裡出現的大樓。`label` 缺 → GIS 名稱 → building_id；`order` 缺 → None
 * （排在有 order 的後面，再依 building_id）。陣列本身已照這個順序排好。
 */
export interface TermRoomBuilding {
  building_id: BuildingId;
  label: Label4;
  order?: Order1;
  [k: string]: unknown;
}
/**
 * v1 `terms/{t}/rooms.json` 的一間：canonical 的 Room ＋ derive 推的 GIS 對應。
 *
 * `gis` 是 list：一個 class_number 可能對到多個多邊形／樓層。`gis_match`：
 *   rule（簡稱規則對到）／override（`reference/gis-room-overrides.json`，GIS 名稱可驗證）／
 *   building_only（只知道哪棟）／floor_only（只知道哪棟哪層）／none（對不到，gis=[]）。
 */
export interface TermRoom {
  code: Code4;
  raw: Raw;
  full_name?: FullName;
  capacity?: Capacity1;
  slots?: Slots;
  gis?: Gis;
  gis_match?: GisMatch;
  [k: string]: unknown;
}
/**
 * 教室某一格（星期×節次）**有排課**。反過來不成立：沒有 slot ≠ 保證空著
 * （社團借用、補課、系上開會都不在課表裡）。同一格可有多門課（例：大學部／研究所合開）。
 */
export interface RoomSlot {
  day: Day1;
  period: Period;
  offering_ids?: OfferingIds1;
  [k: string]: unknown;
}
/**
 * 對到的 GIS 位置。GIS 房間鍵是 (building_id, class_number)——class_number 只在同一棟內唯一；
 * **不用** sourceFeatureId（gid 重新匯入就會變）。building_only／floor_only 時較細的欄位為 None。
 */
export interface RoomGisRef {
  building_id: BuildingId1;
  floor_id?: FloorId;
  class_number?: ClassNumber;
  [k: string]: unknown;
}
